### ISSUE TITLE
Bug To-Do Megaissue

### ISSUE THREAD

**Issue by ikesicle** [RileSamurott/Providirector#6]
This is a list of all of the bugs/missing features that are currently known. They will most likely be fixed in coming updates, but if not they will be indicated as such here.

High-priority bugs/features are bolded.
- [ ] Alternate Control Scheme to allow for the choosing of specific elites rather than Tiers
- [ ] Mithrix and Voidling spawn facing the wrong way
- [ ] **Undefined/Default behaviour on the False Son Stage**
- [ ] **No monster cards being loaded on latest version**
- [ ] Choosing/Taking control of Teleporter Bosses
- [ ] Free-camera mode
- [ ] **Unable to properly control camera (locked in First Person) in latest version**
- [ ] Updating lobby prompts for clarity

## ROADMAP
Before December:
- [ ] Get basic functionality back for the SotS Update
- [ ] Restore configuration options
- [ ] Improve process for choosing director in lobby

If time permits:
- [ ] Implement custom free-cam mode (also leads to controller support)
- [ ] Implement special case behaviour for the False Son stage
- [ ] Implement option to choose the next teleport boss + stage
- [ ] Rework Burst to make it more interactive (wrath?)

**Comment by ikesicle** [comment]
Rescue Ship Bug might need re-verification, nothing in the source suggests that the rescue ship should break the game like it reportedly does

**Comment by MagentaLizard** [comment]
Thanks so much for the update!! Will voidling be re-enabled in the future if you're able to make him less clunky in 3rd person?

**Comment by ikesicle** [comment]
@MagentaLizard 
> Thanks so much for the update!! Will voidling be re-enabled in the future if you're able to make him less clunky in 3rd person?

Maybe, although I just don't think controlling Voidling is as fun as controlling Mithrix, at least in 3rd person. If I can figure out a way to force the camera to be first person instead (First person mod?), I think I'll re-enable him; otherwise, controlling Voidling as a player is just not great. I won't go into detail on how, but if you played any of the 0.2 versions and got to Voidling, I'm sure you know what I'm alluding to.

**Comment by MagentaLizard** [comment]
> @MagentaLizard
> 
> > Thanks so much for the update!! Will voidling be re-enabled in the future if you're able to make him less clunky in 3rd person?
> 
> Maybe, although I just don't think controlling Voidling is as fun as controlling Mithrix, at least in 3rd person. If I can figure out a way to force the camera to be first person instead (First person mod?), I think I'll re-enable him; otherwise, controlling Voidling as a player is just not great. I won't go into detail on how, but if you played any of the 0.2 versions and got to Voidling, I'm sure you know what I'm alluding to.

Yeah it was pretty difficult to aim some of the attacks and some attacks would let you keep moving when you were supposed to be still.
